const productos = [
    {
        id: 001,
        nombre: "platos",
        precio: 200,
        descripcion: "juego de platos",
        categoria: "vajilla",
        oferta: false,
    },
    {
        id: 002,
        nombre: "vasos",
        precio: 150,
        descripcion: "juego de vasos",
        categoria: "vajilla",
        oferta: false,
    },
    {
        id: 003,
        nombre: "cubiertos",
        precio: 100,
        descripcion: "par de cubiertos",
        categoria: "cubiertos",
        oferta: true,
    },
    {
        id: 004,
        nombre: "tazas",
        precio: 180,
        descripcion: "tazas buena calidad",
        categoria: "vajilla",
        oferta: false,
    },
    {
        id: 005,
        nombre: "tazas chinas",
        precio: 80,
        descripcion: "tazas chinas",
        categoria: "vajilla",
        oferta: true,
    },
    {
        id: 006,
        nombre: "platillos chinos",
        precio: 120,
        descripcion: "para las tazas chinas",
        categoria: "vajilla",
        oferta: false,
    },
    {
        id: 007,
        nombre: "juguera",
        precio: 200,
        descripcion: "para hacer jugos naturales",
        categoria: "accesorios",
        oferta: true,
    },
    {
        id: 008,
        nombre: "sopera",
        precio: 1000,
        descripcion: "sopera antigua",
        categoria: "vajilla",
        oferta: false,
    },
    {
        id: 009,
        nombre: "rallador",
        precio: 135,
        descripcion: "ralla fino y grueso",
        categoria: "accesorios",
        oferta: false,
    },
    {
        id: 010,
        nombre: "cuchilla",
        precio: 250,
        descripcion: "cuchilla de cocina",
        categoria: "cubiertos",
        oferta: false,
    },
    {
        id: 011,
        nombre: "posa vaso",
        precio: 50,
        descripcion: "para posar los vasos",
        categoria: "accesorios",
        oferta: false,
    },
    {
        id: 012,
        nombre: "panera",
        precio: 120,
        descripcion: "para servir el pan",
        categoria: "accesorios",
        oferta: true,
    },
    {
        id: 013,
        nombre: "huevera",
        precio: 150,
        descripcion: "para guardar los huevos",
        categoria: "accesorios",
        oferta: false,
    },
    {
        id: 014,
        nombre: "cucharon",
        precio: 95,
        descripcion: "para revolver",
        categoria: "accesorios",
        oferta: false,
    },
    {
        id: 015,
        nombre: "postrera",
        precio: 80,
        descripcion: "para servir el postre",
        categoria: "vajilla",
        oferta: false,
    }
]